apiVersion: v1
kind: Secret
metadata:
  name: client-cert-key
  labels:
    {{- include "auditor-apel.labels" . | nindent 4 }}
data:
  client.key: |-
    {{- .Files.Get "files/client.key" | nindent 4 }}
