[package]
name = "auditor-slurm-collector"
version = "0.0.6"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Slurm collector for AUDITOR"
documentation = "https://docs.rs/auditor/"
homepage = "https://alu-schumacher.github.io/AUDITOR/"
repository = "https://github.com/alu-schumacher/AUDITOR"
readme = "../../README.md"
keywords = ["accounting", "opportunistic", "grid-computing", "batch-systems"]
exclude = [
    ".cargo",
    ".dockerignore",
    ".git",
    ".gitattributes",
    ".github",
    ".gitignore",
    ".pytest_cache",
    "target",
    "nohup.out"
]

[[bin]]
name = "auditor-slurm-collector"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
auditor = { path = "../../auditor", version = "0.0.6", default-features = false, features = ["client"] }
bincode = "1.3.3"
color-eyre = "0.6.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "process"] }
tracing = { version = "0.1", features = ["log"] }
uuid = { version = "1.1", features = ["v4"] }
fake = { version = "2.5", features = ["chrono"] }
config = "0.13.2"
serde = { version = "1.0.151", features = ["derive"] }
serde-aux = "4.0.0"
itertools = "0.10.5"
regex = "1.7.0"
chrono = "0.4.23"
once_cell = "1.17.0"
serde_with = { version = "2.1.0", features = ["chrono_0_4"] }

[dependencies.sqlx]
version = "0.6.2"
default-features = false
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "sqlite",
    "uuid",
    "chrono",
    "migrate",
    "offline"
]

[dev-dependencies]
