apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "auditor-collector.clusterRoleName" . }}
  labels:
    {{- include "auditor-collector.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.clusterRole.annotations | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - pods
  verbs:
    - 'get'
    - 'list'
#- apiGroups: ["kube.rs"]
#  resources:
#    - "documents"
#    - "documents/status"
#  verbs:
#    - "get"
#    - "list"
