apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auditor-collector.serviceAccountName" . }}
  labels:
    {{- include "auditor-collector.labels" . | nindent 4 }}
  annotations: 
    {{- toYaml .Values.serviceAccount.annotations.toYaml | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
