application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "auditor"
metrics:
  database:
    frequency: 30
    metrics:
      - RecordCount
      - RecordCountPerSite
      - RecordCountPerGroup
      - RecordCountPerUser
tls_config:
  use_tls: true
  ca_cert_path: "./auditor/certs/rootCA.pem"
  server_cert_path: "./auditor/certs/server-cert.pem"
  server_key_path: "./auditor/certs/server-key.pem"
