apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auditor.fullname" . }}
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
data:
  auditor.yml: |-
    application:
      addr: 0.0.0.0
      port: 8000
    database:
      host: "{{ .Values.postgres.host }}"
      port: {{ .Values.postgres.port }}
      username: "{{ .Values.postgres.user }}"
      password: "{{ .Values.postgres.password }}"
      database_name: "{{ .Values.postgres.dbName }}"
      require_ssl: "{{ .Values.postgres.requireSsl }}"
    metrics:
      database:
        frequency: 60
        metrics:
          - RecordCount
          - RecordCountPerSite
          - RecordCountPerGroup
          - RecordCountPerUser
    log_level: {{ default "info" .Values.auditor.config.logLevel }}
