# Default values for auditor-apel.

# nameOverride overrides the name of the chart
nameOverride: ""
# fullnameOverride overrides the fully qualified name of the chart
fullnameOverride: ""

## Image to use
registry: null
repository: "aluschumacher/auditor-apel-plugin"
# Overrides the image tag whose default is the chart appVersion.
tag: null
pullPolicy: IfNotPresent

apelPlugin:
  annotations: {}
  uid: 65534
  gid: 65534

persistentVolume:
  use: false
  #annotations:
  #  pv.beta.kubernetes.io/gid: "210"
  size: "100Mi"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [""]
  type:
    local:
      path: /srv/auditor/apel

# The configuration options are explained at
# https://alu-schumacher.github.io/AUDITOR//latest/#apel-plugin
config:
  plugin:
    log_level: INFO
    time_json_path: /auditor/data/time.json
    report_interval: 60
    message_type: summaries

  site:
    publish_since: 2024-07-17 06:00:00Z
    sites_to_report:
      # GOC to auditor
      wuppertalprod: ["wuppertal"]

  authentication:
    auth_url: https://msg.argo.grnet.gr:8443/v1/service-types/ams/hosts/msg.argo.grnet.gr:authx509
    ams_url: https://msg-devel.argo.grnet.gr:443/v1/projects/accounting/topics/gLite-APEL:publish?key=
    client_cert: /auditor/client.pem
    client_key: /auditor/client.key
    ca_path: /auditor/ca.pem
    verify_ca: False

  auditor:
    # Set by the parent chart. Use if you want this chart as stand-alone.
    ip:
    port: 8000
    timeout: 60
    site_meta_field: site_id

  summary_fields:
    mandatory:
      NormalisedWallDuration: !NormalisedWallDurationField
        datatype_in_message: INT
        score:
          #name: hepscore23
          name: HEPSPEC06
          datatype_in_message: FLOAT
          component_name: Cores
      CpuDuration: !ComponentField
        name: TotalCPU
        datatype_in_message: INT
        divide_by: 1000
      NormalisedCpuDuration: !NormalisedField
        datatype_in_message: INT
        base_value: !ComponentField
          name: TotalCPU
          datatype_in_message: INT
          divide_by: 1000
        score:
          # name: hepscore23
          name: HEPSPEC06
          datatype_in_message: FLOAT
          component_name: Cores
      
    optional:
      #GlobalUserName: !MetaField
      #  name: subject
      #  datatype_in_message: TEXT
      #VO: !MetaField
      #  name: voms
      #  datatype_in_message: TEXT
      #  regex: (?<=%2F).*?\S(?=%2F)
      VO: !ConstantField
        value: atlas
        datatype_in_message: TEXT
      #VOGroup: !MetaField
      #  name: voms
      #  datatype_in_message: TEXT
      #  regex: (?=%2F).*?\S(?=%2F)
      #VORole: !MetaField
      #  name: voms
      #  datatype_in_message: TEXT
      #  regex: (?=Role).*
      #SubmitHost: !MetaField
      #  name: headnode
      #  datatype_in_message: TEXT
      Infrastructure: !ConstantField
        value: grid
        datatype_in_message: TEXT
      NodeCount: !ComponentField
        name: NNodes
        datatype_in_message: INT
      Processors: !ComponentField
        name: Cores
        datatype_in_message: INT

  individual_job_fields:
    mandatory:
      CpuDuration: !ComponentField
        name: TotalCPU
        datatype_in_message: INT
        divide_by: 1000

    optional:
      GlobalUserName: !MetaField
        name: subject
        datatype_in_message: TEXT
      VO: !MetaField
        name: voms
        datatype_in_message: TEXT
        regex: (?<=%2F).*?\S(?=%2F)
      VOGroup: !MetaField
        name: voms
        datatype_in_message: TEXT
        regex: (?=%2F).*?\S(?=%2F)
      VORole: !MetaField
        name: voms
        datatype_in_message: TEXT
        regex: (?=Role).*
      SubmitHost: !MetaField
        name: headnode
        datatype_in_message: TEXT
      InfrastructureType: !ConstantField
        value: grid
        datatype_in_message: TEXT
      NodeCount: !ComponentField
        name: NNodes
        datatype_in_message: INT
      Processors: !ComponentField
        name: Cores
        datatype_in_message: INT
      LocalUserId: !MetaField
        name: user_id
        datatype_in_message: TEXT
      FQAN: !MetaField
        name: voms
        datatype_in_message: TEXT
      InfrastructureDescription: !ConstantField
        value: AUDITOR-ARC-SLURM
        datatype_in_message: TEXT
      ServiceLevel: !ScoreField
        name: hepscore23
        datatype_in_message: FLOAT
        component_name: Cores
      ServiceLevelType: !ConstantField
        value: hepscore23
        datatype_in_message: TEXT

## End of config ##############################################################

