addr: "host.docker.internal"
port: 8000
record_prefix: "slurm"
site_id: "site"
components:
  - name: "Cores"
    key: "NCPUS"
    scores:
      - name: "HEPSPECK"
        factor: 1.1
        only_if:
          key: "Partition"
          matches: "^part1$"
  - name: "Cores"
    key: "NCPUS"
    scores:
      - name: "HEPSPECK"
        factor: 1.2
        only_if:
          key: "Partition"
          matches: "^part2$"
  - name: "SystemCPU"
    key: "SystemCPU"
    key_type: Time
    only_if:
      key: "Partition"
      matches: "^part1$"
  - name: "UserCPU"
    key: "UserCPU"
    key_type: Time
    only_if:
      key: "Partition"
      matches: "^part1$"
  - name: "Memory"
    key: "ReqMem"
    key_type: IntegerMega