services:
  slurm:
    image: giovtorres/docker-centos7-slurm:latest
    hostname: slurmctl
    stdin_open: true
    tty: true
    extra_hosts:
      # "host.docker.internal" will resolve to the hosts IP
      - "host.docker.internal:host-gateway"
    # Persistence not wanted.
    # volumes:
    #   - ./volumes/lib:/var/lib/slurmd
    #   - ./volumes/spool:/var/spool/slurm
    #   - ./volumes/log:/var/log/slurm
    #   - ./volumes/db:/var/lib/mysql
