addr: "host.docker.internal"
port: 8000
record_prefix: "slurm"
site_id: "site"
components:
  - name: "Cores"
    key: "NumCPUs"
    scores:
      - name: "HEPSPECK"
        value: 1.1
        only_if:
          key: "Partition"
          matches: "^part1$"
  - name: "Cores"
    key: "NumCPUs"
    scores:
      - name: "HEPSPECK"
        value: 1.2
        only_if:
          key: "Partition"
          matches: "^part2$"
  - name: "Memory"
    key: "Mem"
tls_config:
  use_tls: true
  ca_cert_path: "/client_certs/rootCA.pem"
  client_cert_path: "/client_certs/client-cert.pem"
  client_key_path: "/client_certs/client-key.pem"
