apiVersion: v2
name: auditor-kubernetes-stack
description: AUDITOR collctor stack for Kubernetes
type: application
version: 0.7.0
appVersion: "0.7.0"
kubeVersion: ">=1.28.0-0"
home: https://alu-schumacher.github.io/AUDITOR
dependencies:
- name: auditor
  condition: auditor.enabled
- name: auditor-collector
  condition: auditor-collctor.enabled
- name: auditor-prometheus
  condition: auditor-prometheus.enabled
- name: auditor-apel
  condition: auditor-apel.enabled

