apiVersion: v2
name: auditor-collector
description: AUDITOR collector for Kubernetes
type: application
version: 0.6.2.0
appVersion: "0.6.2"
kubeVersion: ">=1.28.0-0"
home: https://alu-schumacher.github.io/AUDITOR
