# Default values for auditor-collector.

# nameOverride overrides the name of the chart
nameOverride: ""
# fullnameOverride overrides the fully qualified name of the chart
fullnameOverride: ""

## Collector image to use
#registry: "localhost:5000"
registry: ""
repository: "auditor-kubernetes-collector"
# Overrides the image tag whose default is the chart appVersion.
tag: null
pullPolicy: IfNotPresent

collector:
  annotations: {}
  uid: 65534
  gid: 65534
  # Collector config
  # See https://alu-schumacher.github.io/AUDITOR/latest/#collectors
  # Leaving a value empty will apply the default
  config:
    # Is set by the parent chart. Specify, if you want to use this chart
    # as stand-alone.
    auditorAddress:
    auditorPort: 8000
    # Set by the parent chart
    prometheusAddress:
    prometheusPort: 9090
    recordPrefix: KUBE_
    earliestDatetime: ""
    auditorTimeout:
    prometheusTimeout:
    # As in job_filter
    namespaces:
      - default
    # As in job_filter
    labels:
      - app==test
    collectInterval: 60
    mergeInterval: 60
    backlogInterval:
    backlogMaxretries:
    logLevel: info

persistentVolume:
  use: false
  #annotations:
  #  pv.beta.kubernetes.io/gid: "210"
  size: "100Mi"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [""] # Hostname
  type:
    local:
      path: /srv/auditor/collector

serviceAccount:
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set, a name is generated using the fullname template
  name: ""

clusterRole:
  annotations: {}
  # Overrides the default name
  name: ""
