[advisories]
ignore = [
    "RUSTSEC-2020-0071", # `time` localtime_r segfault
    "RUSTSEC-2020-0159", # `chrono` localtime_r segfault
    "RUSTSEC-2022-0090", # sqlite vulnerability, will be fixed with sqlx 0.7
]
