apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auditor-prometheus.serviceAccountName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "auditor-prometheus.serviceAccountName" . }}
type: kubernetes.io/service-account-token
