apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auditor-prometheus.serviceAccountName" . }}
  labels:
    {{- include "auditor-prometheus.labels" . | nindent 4 }}
  annotations: 
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
