name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  prepare-input-parameters:
    uses: ./.github/workflows/prepare_input_parameters.yml

  build-auditor:
    uses: ./.github/workflows/build_auditor.yml

  sqlx:
    uses: ./.github/workflows/sqlx.yml

  build-pyauditor-linux:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    uses: ./.github/workflows/build_pyauditor_linux.yml
    with:
      python-version: ${{ matrix.python-version }}

  build-pyauditor-windows:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    uses: ./.github/workflows/build_pyauditor_windows.yml
    with:
      python-version: ${{ matrix.python-version }}

  build-pyauditor-macos:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    uses: ./.github/workflows/build_pyauditor_macos.yml
    with:
      python-version: ${{ matrix.python-version }}
      
  python-unit-tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    needs: build-pyauditor-linux
    uses: ./.github/workflows/python_unit_tests.yml
    with:
      python-version: ${{ matrix.python-version }}

  pyauditor-docs:
    needs: [build-pyauditor-linux, prepare-input-parameters]
    uses: ./.github/workflows/pyauditor_docs.yml
    with:
      python-version: ${{ needs.prepare-input-parameters.outputs.python_version }}

  pyauditor-integration-tests:
    needs: [build-pyauditor-linux, sqlx, prepare-input-parameters]
    uses: ./.github/workflows/pyauditor_integration_tests.yml
    with:
      python-version: ${{ needs.prepare-input-parameters.outputs.python_version }}

  release-pyauditor:
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [build-pyauditor-linux, build-pyauditor-windows, build-pyauditor-macos, prepare-input-parameters]
    uses: ./.github/workflows/release_pyauditor.yml
    with:
      python-version: ${{ needs.prepare-input-parameters.outputs.python_version }}

  release-python-packages:
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [release-pyauditor, prepare-input-parameters]
    uses: ./.github/workflows/release_python_packages.yml
    with:
      python-version: ${{ needs.prepare-input-parameters.outputs.python_version }}
