name: check-changelog

on:
  pull_request:

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check CHANGELOG.md
        uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md
