name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      SQLX_VERSION: 0.8.5
      SQLX_FEATURES: postgres,rustls,sqlite
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository,
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cache-dependencies

      - name: Massage sqlx features env variable...
        run: |
          TMP=${{ env.SQLX_FEATURES }}
          SQLX_FEATURES_CACHE="${TMP//,/_}"
          echo "SQLX_FEATURES_CACHE=${SQLX_FEATURES_CACHE}" >> $GITHUB_ENV

      - name: Cache sqlx
        id: cache_sqlx
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cache-sqlx
          key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}-${{ env.SQLX_FEATURES_CACHE }}
          cache-directories: |
            ~/.cargo/bin/sqlx
            ~/.cargo/bin/cargo-sqlx

      - name: Install sqlx-cli 
        # if: ${{ steps.cache_sqlx.outputs.cache-hit }}
        run: cargo install sqlx-cli --version=${{ env.SQLX_VERSION }} --features=${{ env.SQLX_FEATURES }} --no-default-features --locked

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Migrate auditor client sqlite database
        run: ./scripts/init_client_sqlite.sh

      - name: Migrate slurm collector sqlite database
        run: |
          ./scripts/init_slurm_collector_sqlite.sh

      - name: Migrate kubernetes collector sqlite database
        run: ./scripts/init_kubernetes_collector_sqlite.sh

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ef0e698e-e1de-4603-88fa-b3d7c10fb0e1
          #${{ secrets.CODECOV_TOKEN }} doesn't work for PRs from forks
