name: priority-plugin

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Priority plugin
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      SQLX_VERSION: 0.8.2
      SQLX_FEATURES: postgres,rustls,sqlite
      RUSTFLAGS: -C link-arg=-s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cache-dependencies

      - name: Massage sqlx features env variable...
        run: |
          TMP=${{ env.SQLX_FEATURES }}
          SQLX_FEATURES_CACHE="${TMP//,/_}"
          echo "SQLX_FEATURES_CACHE=${SQLX_FEATURES_CACHE}" >> $GITHUB_ENV

      - name: Cache sqlx
        id: cache_sqlx
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cache-sqlx
          key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}-${{ env.SQLX_FEATURES_CACHE }}
          cache-directories: |
            ~/.cargo/bin/sqlx
            ~/.cargo/bin/cargo-sqlx

      - name: Install sqlx-cli 
        # if: ${{ steps.cache_sqlx.outputs.cache-hit }}
        run: cargo install sqlx-cli --version=${{ env.SQLX_VERSION }} --features=${{ env.SQLX_FEATURES }} --no-default-features --locked

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Migrate auditor client sqlite database
        run: ./scripts/init_client_sqlite.sh

      - name: Install musl
        run: |
          sudo apt-get install musl musl-tools

      - name: Build auditor
        run: cargo build --bin auditor

      - name: Build priority plugin
        run: cargo build --bin auditor-priority-plugin --target x86_64-unknown-linux-musl

      - name: Test priority plugin
        run: SKIP_COMPILATION=true ./scripts/test_priority_plugin.sh
