name: pyauditor-docs

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  pyauditor-docs:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed "s/main/edge/" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: pyauditor-wheels

      - name: Install pyauditor
        run: |
          pip install --upgrade pip
          ls | grep manylinux | grep 39 | xargs pip install

      - name: Build pyauditor docs
        run: CI_MODE=true SKIP_COMPILATION=true ./scripts/docs_pyauditor.sh

      - name: Deploy pyauditor docs
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pyauditor/docs/_build/html
          target-folder: pyauditor/${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false

      # Only for tag push: Update latest to new release version

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          ref: gh-pages
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Redirect latest to new release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
            echo "Redirecting latest to newly released version " $RELEASE_VERSION
            rm -rf pyauditor/latest
            ln -s pyauditor/$RELEASE_VERSION pyauditor/latest
            git add pyauditor/latest
            git commit -m "CI: Redirect latest to new version $RELEASE_VERSION (pyauditor)"
      - name: Push changes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
