name: pyauditor-docs

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed "s/main/edge/" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: pyauditor-wheels-linux-${{ inputs.python-version }}

      - name: Install pyauditor
        run: |
          pip install --upgrade pip
          pip install *.whl

      - name: Build pyauditor docs
        run: CI_MODE=true SKIP_COMPILATION=true ./scripts/docs_pyauditor.sh

      - name: Deploy pyauditor docs
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pyauditor/docs/_build/html
          target-folder: pyauditor/${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false

      # Only for tag push: Update latest to new release version

  update_latest:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed "s/main/edge/" >> $GITHUB_ENV

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Redirect latest to new release
        working-directory: pyauditor
        run: |
            echo "Redirecting latest to newly released version ${{ env.RELEASE_VERSION}}"
            rm -rf latest
            ln -s $RELEASE_VERSION latest

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "pyauditor/latest"
          message: "CI: Redirect latest to new version ${{ env.RELEASE_VERSION }} (pyauditor)"
          default_author: "github_actions"
          pathspec_error_handling: exitAtEnd

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
