name: pyauditor-integration-tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  pyauditor-integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      SQLX_VERSION: 0.8.2
      SQLX_FEATURES: postgres,rustls,sqlite
      RUSTFLAGS: -C link-arg=-s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-dependencies-pyauditor-integration

      - name: Cache sqlx
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-dependecies-sqlx
          cache-directories: |
            ~/.cargo/bin/sqlx
            ~/.cargo/bin/cargo-sqlx

      - name: Install sqlx-cli 
        run: cargo install sqlx-cli --version=${{ env.SQLX_VERSION }} --features=${{ env.SQLX_FEATURES }} --no-default-features --locked

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Download pyauditor wheel
        uses: actions/download-artifact@v4
        with:
          name: pyauditor-wheels-linux-${{ inputs.python-version }}

      - name: Build auditor
        run: SQLX_OFFLINE=true cargo build --bin auditor

      - name: Install pyauditor and dependencies
        run: |
          pip install --upgrade pip
          pip install *.whl
          pip install tzlocal

      - name: Run integration tests
        run: SKIP_COMPILATION=true SKIP_PYAUDITOR_COMPILATION=true ./scripts/test_pyauditor.sh

      - name: Run tls pyauditor tests
        run: SKIP_COMPILATION=true SKIP_PYAUDITOR_COMPILATION=true ./scripts/test_tls_pyauditor.sh
