name: python-unit-tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        
jobs:
  unit-tests-apel-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/apel
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          path: ./plugins/apel
          name: pyauditor-wheels-linux-${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install *.whl
          pip install -e .[tests]
      - name: Run pytest
        run: pytest
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./plugins/apel/lcov.info
          fail_ci_if_error: true
          token: 0da88fa3-3a98-4f8b-ad19-9d0785b46dbc
          #${{ secrets.CODECOV_TOKEN }} doesn't work for PRs from forks
