name: python-unit-tests

on:
  workflow_run:
    workflows: [build-pyauditor]
    types: [completed]

jobs:
  unit-tests-apel-plugin:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./plugins/apel
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Download artifact'
        uses: actions/github-script@v7
        env:
          WHEEL: linux-wheel-${{matrix.python-version}}
        with:
          script: |
            const { WHEEL } = process.env
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == `${WHEEL}`
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`./plugins/apel/linux-wheel.zip`, Buffer.from(download.data));
      - name: 'Unzip artifact'
        run: unzip linux-wheel.zip
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install *.whl
          pip install -e .[tests]
      - name: Run pytest
        run: pytest
      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lcov-${{ matrix.python-version }}.info
          path: ./plugins/apel/lcov.info
          retention-days: 7

  upload-coverage:
    runs-on: ubuntu-latest
    needs: unit-tests-apel-plugin
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: lcov-${{ matrix.python-version }}.info
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
