name: python-unit-tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests-apel-plugin:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build_pyauditor.yml
    defaults:
      run:
        working-directory: ./plugins/apel
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-wheel-${{ matrix.python-version }}-${{github.sha}}
          path: ./plugins/apel/linux-wheel.zip
      - name: Unzip artifact
        run: unzip linux-wheel.zip
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install *.whl
          pip install -e .[tests]
      - name: Run pytest
        run: pytest
      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lcov-${{ matrix.python-version }}.info
          path: ./plugins/apel/lcov.info
          retention-days: 7

  upload-coverage:
    runs-on: ubuntu-latest
    needs: unit-tests-apel-plugin
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: lcov-${{ matrix.python-version }}.info
          path: lcov.info
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
