name: release-python-packages

on:
  workflow_call:

jobs:
  build-apel-plugin-py:
    runs-on: ubuntu-latest
    container: almalinux:9
    defaults:
      run:
        working-directory: ./plugins/apel
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          dnf install -y python3-pip
          pip install --upgrade pip
          pip install build
      - name: Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./plugins/apel/dist
          name: apel-plugin-release

  publish-apel-plugin-pip:
    needs: build-apel-plugin-py
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v8
        with:
          path: ./plugins/apel/dist
          name: apel-plugin-release
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: plugins/apel/dist/
          attestations: false
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: plugins/apel/dist/*
    

  publish-apel-plugin-rpm:
    needs: publish-apel-plugin-pip
    runs-on: ubuntu-latest
    container: almalinux:9
    defaults:
      run:
        working-directory: ./plugins/apel
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          dnf install -y epel-release dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf install -y python3-pip rpm-build python3-virtualenv
          dnf groupinstall -y "Development Tools"
          pip install --upgrade pip
          pip install uv rpmvenv
      - name: Build RPM
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          echo "." >> requirements.txt
          cat requirements.txt
          QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: plugins/apel/*rpm

  build-htcondor-collector-py:
    runs-on: ubuntu-latest
    container: almalinux:9
    defaults:
      run:
        working-directory: ./collectors/htcondor
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          dnf install -y python3-pip
          pip install --upgrade pip
          pip install build
      - name: Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./collectors/htcondor/dist
          name: htcondor-collector-release

  publish-htcondor-collector-pip:
    needs: build-htcondor-collector-py
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v8
        with:
          path: ./collectors/htcondor/dist
          name: htcondor-collector-release
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: collectors/htcondor/dist/
          attestations: false
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: collectors/htcondor/dist/*
    

  publish-htcondor-collector-rpm:
    needs: publish-htcondor-collector-pip
    runs-on: ubuntu-latest
    container: almalinux:9
    defaults:
      run:
        working-directory: ./collectors/htcondor
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          dnf install -y epel-release dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf install -y python3-pip rpm-build python3-virtualenv
          dnf groupinstall -y "Development Tools"
          pip install --upgrade pip
          pip install uv rpmvenv
      - name: Build RPM
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          echo "." >> requirements.txt
          cat requirements.txt
          QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: collectors/htcondor/*rpm

  build-utilization-plugin-py:
    runs-on: ubuntu-latest
    container: almalinux:9
    defaults:
      run:
        working-directory: ./plugins/utilization_tool
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          dnf install -y python3-pip
          pip install --upgrade pip
          pip install build
      - name: Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./plugins/utilization_tool/dist
          name: utilization-plugin-release

  publish-utilization-plugin-pip:
    needs: build-utilization-plugin-py
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v8
        with:
          path: ./plugins/utilization_tool/dist
          name: utilization-plugin-release
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: plugins/utilization_tool/dist/
          attestations: false
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: plugins/utilization_tool/dist/*
    

  publish-utilization-plugin-rpm:
    needs: publish-utilization-plugin-pip
    runs-on: ubuntu-latest
    container: almalinux:9
    defaults:
      run:
        working-directory: ./plugins/utilization_tool
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          dnf install -y epel-release dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf install -y python3-pip rpm-build python3-virtualenv
          dnf groupinstall -y "Development Tools"
          pip install --upgrade pip
          pip install uv rpmvenv
      - name: Build RPM
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          echo "." >> requirements.txt
          cat requirements.txt
          QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: plugins/utilization_tool/*rpm
