name: release-python-packages

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  release-apel-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/apel
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[build] uv rpmvenv
      - name: Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: plugins/apel/dist/
          attestations: false
      - name: Build RPM
        uses: nick-fields/retry@v3
        with:
          max_attempts: 100
          timeout_seconds: 20
          command: |
            cd /home/runner/work/AUDITOR/AUDITOR/plugins/apel
            uv pip compile pyproject.toml -o requirements.txt
            echo "." >> requirements.txt
            cat requirements.txt
            QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
          new_command_on_retry: |
            cd /home/runner/work/AUDITOR/AUDITOR/plugins/apel
            QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            plugins/apel/dist/*
            plugins/apel/*rpm
          
  release-htcondor-collector:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./collectors/htcondor
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[build] uv rpmvenv
      - name: Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: collectors/htcondor/dist/
          attestations: false
      - name: Build RPM
        uses: nick-fields/retry@v3
        with:
          max_attempts: 100
          timeout_seconds: 20
          command: |
            cd /home/runner/work/AUDITOR/AUDITOR/collectors/htcondor
            uv pip compile pyproject.toml -o requirements.txt
            echo "." >> requirements.txt
            cat requirements.txt
            QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
          new_command_on_retry: |
            cd /home/runner/work/AUDITOR/AUDITOR/collectors/htcondor
            QA_SKIP_BUILD_ROOT=1 rpmvenv --verbose rpm_config.json
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            collectors/htcondor/dist/*
            collectors/htcondor/*rpm
