name: Release

on:
  workflow_call:

jobs:
  release-pyauditor:
    runs-on: ubuntu-latest
    steps:
      - name: Download pyauditor wheels
        uses: actions/download-artifact@v3
        with:
          name: pyauditor-wheels

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *
