name: release-pyauditor

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  release-pyauditor:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download pyauditor wheels
        uses: actions/download-artifact@v4
        with:
          pattern: pyauditor-wheels-*
          path: dist
          merge-multiple: true

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
