name: Website

on: 
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Build only 
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: media/website
          BUILD_ONLY: true
          OUT_DIR: public
          # BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          folder: media/website/public
          target-folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
